### PR TITLE
(2021-01-16) Implement osu!std pp changes

### PR DESCRIPTION
**Pull request by KotRikD**
Hi! The PR is aimed at implementing the latest pp changes, I'm not a good C programmer, so I think there may be errors and improper formatting. Otherwise, tested on a couple of scores:

- the whitecat 1 089 pp play: [picture comparing original osu tools and oppai ng](https://baka-ero.kotworks.cyou/new/3XqmnATZdZ.png)
- non-funny play aimed at nf pp and hd perfomance:  [picture](https://baka-ero.kotworks.cyou/new/hv9aQSgfqF.png)
- and non-funny bad scores with big count misses and low acc: [picture](https://baka-ero.kotworks.cyou/new/foE7U8I7m4.png)
- mrekk's top 5 scores, whitecat's top 4 scores: (There will be no references, I tested through gosumemory with that calculations)

### CODE REVIEW

**Comment by Francesco149** [comment]
I'll merge when I have regenerated the test suite but it looks good so far

**Comment by KotRikD** [comment]
Be careful, I was trying to generate a test suite yesterday, some scores still hasn't been recalculated on bancho.

**Comment by MaxKruse** [comment]
I tried manually generating the test suite, but something broke. probably error on my end. As far as i know, bancho recalc for the top ~20k players has finished.

**Comment by KotRikD** [comment]
@MaxKruse https://ghostbin.co/paste/ah52d I fixed this mistake here, try it!

**Comment by MaxKruse** [comment]
PP Recalc is done, packing is possible. Pre-packed: https://lithibae.s-ul.eu/8D5oqmLT

**Comment by Francesco149** [comment]
can confirm that 2153557 is still not recalculated as @KotRikD said, need to figure out how to generate a good enough test suite for now that doesn't include old scores

**Comment by Francesco149** [comment]
even if i pick pretty new maps there's still many scores that aren't recalced hmmm

**Comment by Francesco149** [comment]
if I include only the current top 10 or so's top plays the tests pass, let's use that as the temporary test suite

**Pull request merged**
