### PR TITLE
Replace build script with Makefile, add shared library generation

### PR DESCRIPTION
**Pull request by christopher-dG**
Nice work on the rewrite! 

I guess this undoes my last PR, but oh well :sweat_smile:.

This works on my machine, you should definitely test it on yours too. I figured that now that there's more than one build configuration, a Makefile would be a lot easier to maintain.

### CODE REVIEW

**Comment by Francesco149** [comment]
sorry, but I don't plan on using a makefile for oppai. I find the shell script much simpler to read and use and I don't need partial compiles anyways.

thanks for the effort though!

**Comment by Francesco149** [comment]
also for the shared library, I don't think it would be usable unless you edit oppai code to export the functions, and it's better used as a single file include anyways

**Comment by christopher-dG** [comment]
No worries :+1:  I've had no problems using Julia `ccall` on the shared library so far!

**Comment by Francesco149** [comment]
oh, well then maybe the explicit exports thing was a c++ thing. can't remember. it would still need ```__declspec(dllexport)``` or whatever on windows when compiling with msvc and whatnot.

I might consider a shared lib build some day, but usually if you are making bindings it's best to make a wrapper library yourself or simply flat out include oppai.c and compile as shared library if the lang supports just straight up invoking funcs from a shared library like C#'s pinvoke

**Pull request closed without merging**
