### PR TITLE
HD nerf

### PR DESCRIPTION
**Pull request by ilyt**
yeah

### CODE REVIEW

**Comment by KedamaOvO** [comment]
pp->speed should be multiplied 1.18 on hidden mod

**Comment by Francesco149** [comment]
by the way this is only the AR HD rebalance, there's also the other more important rebalance that swaps aim/speed multipliers for HD

either way, I can add that easily when I merge

**Comment by ilyt** [comment]
I'll fix the pp->speed @KedamaOwO

**Comment by Francesco149** [comment]
it's fine I already fixed it in my local branch, just working on the test suite atm before I commit

**Comment by ilyt** [comment]
fair enough, ill add it anyway so its just a matter of pulling it.

**Comment by ilyt** [comment]
There we go

**Comment by Francesco149** [comment]
that's taiko pp you edited lol

well it's ok ill try to undo that commit when i merge

**Comment by ilyt** [comment]
Wait is it, im stupid

**Pull request merged**
