### PR TITLE
Update PP calculation

### PR DESCRIPTION
**Pull request by oSumAtrIX**
RE: #81 

This PR updates `oppai.c` to calculate according to the latest pp changes.

Thanks to @l3lackShark

### CODE REVIEW

**Comment by Francesco149** [comment]
all the code style changes are generating useless diff's and make it difficult to tell what actually changed. minimize the diff

**Comment by oSumAtrIX** [comment]
Should the commit be splitted into two, one for formatting and one for the pp update?

A default formatter should be introduced like [ClangFormat](https://clang.llvm.org/docs/ClangFormat.html).

**Comment by Francesco149** [comment]
no code formatting changes pls

**Comment by l3lackShark** [comment]
@oSumAtrIX I have no idea how I contributed to this but if i somehow did - Thanks! Are you going to push these changes later? What was the reason to close the PR?

**Comment by oSumAtrIX** [comment]
> @oSumAtrIX I have no idea how I contributed to this but if I somehow did - Thanks! Are you going to push these changes later? What was the reason to close the PR?

Thank you for your contribution. It seemed like the calculation was not correct.

**Pull request closed without merging**
