### PR TITLE
2018-2019 pp changes

### PR DESCRIPTION
**Pull request by Francesco149**
don't merge until we have official data for the test suite

### CODE REVIEW

**Comment by Francesco149** [comment]
gonna use this branch for all the pp changes, WIP...

**Comment by Francesco149** [comment]
it might also be that due to the lack of slider calculations, the angle value is off enough to mess it up, will try to approximate slider tail

**Comment by Francesco149** [comment]
seems closer now, will still try approximating slider tails though

**Comment by Francesco149** [comment]
nevermind i fixed it, now it matches smoogi's site closely B)

**Comment by Francesco149** [comment]
note to self: squash all commits after https://github.com/Francesco149/oppai-ng/pull/40/commits/4f375ab5d00d644dba29a5deced8be2cad30f16a before merging

**Comment by Francesco149** [comment]
need to add this https://github.com/ppy/osu-performance/commit/2f0fc7b1fa84dfe07e3f475e38dd3bf83fe92193

**Comment by Francesco149** [comment]
also need to check if the latest commits here affect anything https://github.com/ppy/osu/pull/3839

**Comment by Francesco149** [comment]
> need to add this [ppy/osu-performance@2f0fc7b](https://github.com/ppy/osu-performance/commit/2f0fc7b1fa84dfe07e3f475e38dd3bf83fe92193)

now that I look at it more closely it seems to be just a refactor and effectively does nothing

**Comment by Francesco149** [comment]
> also need to check if the latest commits here affect anything [ppy/osu#3839](https://github.com/ppy/osu/pull/3839)

seems like it's just refactoring, guess ill start porting this to other versions of oppai

**Comment by Francesco149** [comment]
cleaned up commit history

**Comment by MaxKruse** [comment]
Dad pp is finalized, pls push :*

**Comment by Francesco149** [comment]
cant yet because not all scores are recalculated (for example freedom dive is still 820)

**Comment by Francesco149** [comment]
sooo defenders is quite a bit off, ill see if i can improve it before merging

**Comment by Francesco149** [comment]
ooooh the high CS bonus was completely wrong, now it's close :ok_hand:

**Comment by Francesco149** [comment]
average error is 1.1%, worst error is 5.9% on death dance due to missing slider calcs. most maps arent that bad though, pretty happy with it

**Comment by MaxKruse** [comment]
rip fopen()

**Pull request merged**
