### PR TITLE
Add Rust implementation to README.md

### PR DESCRIPTION
**Pull request by recapitalverb**
I'm brewing up a Rust implementation of this library over at https://gitlab.com/JackRedstonia/ezpp/. However, it is still a work-in-progress, so I am keeping this pull request as a draft until it is ready for others to use.

### CODE REVIEW

**Comment by recapitalverb** [comment]
This is a "port a C library to Rust but you use the Java port as reference and mid-way you find a way to optimise the entire difficulty calculator to be faster than the C implementation" moment.

I'm not even kidding.

**Comment by recapitalverb** [comment]
@Francesco149 I have gotten basic testing going, needs `osu_files` folder and an osu!api v2 application for API. Both pp and difficulty calculations are way too imprecise IMO, I had to set pp margin to +-10% for the tests to pass. Could you check the code to see why?

**Comment by recapitalverb** [comment]
The library is now ready for use, but I will continue to work on this library to improve performance and code quality. Thanks a lot for the C and Java implementation which I used as reference.

**Comment by Francesco149** [comment]
oh nice i will take a look in a couple hrs

**Comment by Francesco149** [comment]
cool, it seems like a nice and compact implementation

**Pull request merged**
